-- Portal de Casos - Supabase schema
-- Rode este arquivo no SQL Editor do Supabase do projeto novo.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Nome exibido no admin e no portal.
  name text not null,

  -- Board principal/fallback do Monday. Mantemos camelCase porque o app ja usa boardId.
  "boardId" text not null,

  -- Token unico que forma o link publico:
  -- https://app.com/#/casos/<case_public_token>
  case_public_token text not null unique,

  -- Board de casos no Monday. Se vazio, o app usa boardId.
  case_board_id text,

  -- Valor gravado/filtrado na coluna Cliente do Monday.
  -- Se vazio, o app usa name.
  case_client_label text,

  -- Pasta do cliente no Google Drive.
  -- ID da pasta, nao o nome.
  drive_folder_id text,

  -- Campos de espelho operacional no Monday.
  monday_board_id text,
  monday_client_label text,

  portal_password text,

  active boolean not null default true
);

alter table public.clients add column if not exists monday_board_id text;
alter table public.clients add column if not exists monday_client_label text;

create index if not exists clients_case_public_token_idx
  on public.clients (case_public_token);

create index if not exists clients_board_id_idx
  on public.clients ("boardId");

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at
before update on public.clients
for each row
execute function public.set_updated_at();

alter table public.clients enable row level security;

-- Importante:
-- Nao criamos policy de SELECT para anon aqui.
-- O frontend publico deve buscar cliente apenas pela RPC get_client_by_case_token.
-- A API admin usa SUPABASE_SERVICE_ROLE_KEY e ignora RLS.

drop policy if exists "No public direct access to clients" on public.clients;
create policy "No public direct access to clients"
  on public.clients
  for all
  using (false)
  with check (false);

create or replace function public.get_client_by_case_token(p_token text)
returns table (
  id bigint,
  name text,
  "boardId" text,
  case_public_token text,
  case_board_id text,
  case_client_label text,
  drive_folder_id text,
  monday_board_id text,
  monday_client_label text,
  portal_password text,
  active boolean
)
language sql
security definer
set search_path = public
as $$
  select
    c.id,
    c.name,
    c."boardId",
    c.case_public_token,
    c.case_board_id,
    c.case_client_label,
    c.drive_folder_id,
    c.monday_board_id,
    c.monday_client_label,
    c.portal_password,
    c.active
  from public.clients c
  where c.case_public_token = p_token
    and c.active = true
  limit 1;
$$;

revoke all on function public.get_client_by_case_token(text) from public;
grant execute on function public.get_client_by_case_token(text) to anon, authenticated;

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  client_id bigint not null references public.clients(id) on delete cascade,

  patient_name text not null,
  age integer,
  birth_date date,
  gender text,
  procedure text,
  keywords text,
  procedure_description text,
  notes text,

  status text not null default 'em_andamento',
  drive_folder_id text,
  monday_item_id text
);

alter table public.cases add column if not exists birth_date date;
alter table public.cases add column if not exists keywords text;

create index if not exists cases_client_id_idx
  on public.cases (client_id);

create index if not exists cases_created_at_idx
  on public.cases (created_at desc);

drop trigger if exists cases_set_updated_at on public.cases;
create trigger cases_set_updated_at
before update on public.cases
for each row
execute function public.set_updated_at();

create table if not exists public.case_stages (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  case_id uuid not null references public.cases(id) on delete cascade,

  stage_key text not null,
  stage_name text not null,
  moment text,
  sort_order integer not null,
  status text not null default 'fazer',
  drive_folder_id text,
  monday_subitem_id text,

  unique(case_id, stage_key)
);

alter table public.case_stages add column if not exists moment text;

create index if not exists case_stages_case_id_idx
  on public.case_stages (case_id);

drop trigger if exists case_stages_set_updated_at on public.case_stages;
create trigger case_stages_set_updated_at
before update on public.case_stages
for each row
execute function public.set_updated_at();

create table if not exists public.case_files (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  client_id bigint not null references public.clients(id) on delete cascade,
  case_id uuid not null references public.cases(id) on delete cascade,
  stage_id uuid not null references public.case_stages(id) on delete cascade,

  drive_file_id text not null unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint,
  web_view_link text,
  web_content_link text
);

create index if not exists case_files_case_id_idx
  on public.case_files (case_id);

create index if not exists case_files_stage_id_idx
  on public.case_files (stage_id);

create index if not exists case_files_client_id_idx
  on public.case_files (client_id);

alter table public.cases enable row level security;
alter table public.case_stages enable row level security;
alter table public.case_files enable row level security;

drop policy if exists "No public direct access to cases" on public.cases;
create policy "No public direct access to cases"
  on public.cases
  for all
  using (false)
  with check (false);

drop policy if exists "No public direct access to case_stages" on public.case_stages;
create policy "No public direct access to case_stages"
  on public.case_stages
  for all
  using (false)
  with check (false);

drop policy if exists "No public direct access to case_files" on public.case_files;
create policy "No public direct access to case_files"
  on public.case_files
  for all
  using (false)
  with check (false);
