create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  "boardId" text not null,
  avatar_url text,
  case_public_token text not null unique,
  case_board_id text,
  case_client_label text,
  drive_folder_id text,
  active boolean not null default true
);

create index if not exists clients_case_public_token_idx
  on public.clients (case_public_token);

create index if not exists clients_board_id_idx
  on public.clients ("boardId");

alter table public.clients enable row level security;

drop policy if exists "Public can read active clients by token" on public.clients;
create policy "Public can read active clients by token"
  on public.clients
  for select
  using (active = true);

